---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: applicationname-web
spec:
  parentRefs:
    - name: '{{GATEWAY-NAME}}'
      namespace: '{{GATEWAY-NAMESPACE}}'
  hostnames:
    - applicationname.kube.local
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: applicationname-web
          port: 80
